# This is a basic workflow to help you get started with Actions

name: FirstCIAmit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: upload artificat
        uses: actions/upload-artifact@master
        with:
          name: amitartifact
          path: linkedService/
          
      # Pass parameters between steps.    
      - run: |
          export FOO=bar
          echo "::set-env name=FOO::$FOO"
          
      - run: echo $FOO
          
  Testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@master
        with:
          name: amitartifact
          path: linkedService

      # Runs a single command using the runners shell
      - name: Run single line script
        run: echo Hello, world!
        
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}  
